import Club from '#models/club'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class ClubsSeeder extends BaseSeeder {
  public async run() {
    const clubs = [
      {
        name: 'Paris Athletic Club',
        description: 'Club multisport du centre-ville de Paris.',
        type: 'football',
        email: 'contact@parisac.fr',
        phone: '01 45 78 23 11',
        websiteUrl: 'https://parisac.fr',
        addressLine1: '12 Rue des Francs Bourgeois',
        addressLine2: '',
        postalCode: '75003',
        city: 'Paris',
        country: 'France',
        latitude: 48.859,
        longitude: 2.361,
        isActive: true,
      },
      {
        name: 'Olympique Lyonnais Amateur',
        description: 'Section amateur du célèbre club lyonnais.',
        type: 'football',
        email: 'info@olamateur.fr',
        phone: '04 72 10 45 32',
        websiteUrl: 'https://olamateur.fr',
        addressLine1: '350 Avenue Jean Jaurès',
        addressLine2: '',
        postalCode: '69007',
        city: 'Lyon',
        country: 'France',
        latitude: 45.7407,
        longitude: 4.8257,
        isActive: true,
      },
      {
        name: 'Marseille Tennis Club',
        description: 'Club de tennis avec terrains intérieurs et extérieurs.',
        type: 'tennis',
        email: 'contact@marseilletennis.fr',
        phone: '04 91 87 55 11',
        websiteUrl: 'https://marseilletennis.fr',
        addressLine1: '25 Boulevard Michelet',
        addressLine2: '',
        postalCode: '13008',
        city: 'Marseille',
        country: 'France',
        latitude: 43.2706,
        longitude: 5.3957,
        isActive: true,
      },
      {
        name: 'Toulouse Natation Club',
        description: 'Club de natation ouvert à tous les niveaux.',
        type: 'swimming',
        email: 'contact@toulousenatation.fr',
        phone: '05 61 12 75 66',
        websiteUrl: 'https://toulousenatation.fr',
        addressLine1: '15 Rue du Rempart Saint-Étienne',
        addressLine2: '',
        postalCode: '31000',
        city: 'Toulouse',
        country: 'France',
        latitude: 43.6009,
        longitude: 1.444,
        isActive: true,
      },
      {
        name: 'Lille Rugby Métropole',
        description: 'Club de rugby ambitieux de la région lilloise.',
        type: 'rugby',
        email: 'contact@lillerugby.fr',
        phone: '03 20 77 45 65',
        websiteUrl: 'https://lillerugby.fr',
        addressLine1: '92 Rue du Faubourg de Roubaix',
        addressLine2: '',
        postalCode: '59800',
        city: 'Lille',
        country: 'France',
        latitude: 50.632,
        longitude: 3.070,
        isActive: true,
      },
      {
        name: 'Nice Triathlon Club',
        description: 'Club spécialisé triathlon, ouvert à tous.',
        type: 'triathlon',
        email: 'info@nicetriathlon.fr',
        phone: '04 93 55 14 88',
        websiteUrl: 'https://nicetriathlon.fr',
        addressLine1: '8 Avenue Jean Médecin',
        addressLine2: '',
        postalCode: '06000',
        city: 'Nice',
        country: 'France',
        latitude: 43.7013,
        longitude: 7.2663,
        isActive: true,
      },
      {
        name: 'Bordeaux Volley Club',
        description: 'Club de volley dynamique de Nouvelle-Aquitaine.',
        type: 'volleyball',
        email: 'contact@bordeauxvolley.fr',
        phone: '05 56 89 41 22',
        websiteUrl: 'https://bordeauxvolley.fr',
        addressLine1: '41 Rue Georges Bonnac',
        addressLine2: '',
        postalCode: '33000',
        city: 'Bordeaux',
        country: 'France',
        latitude: 44.8412,
        longitude: -0.5806,
        isActive: true,
      },
      {
        name: 'Strasbourg Escrime Club',
        description: 'Club d’escrime historique de Strasbourg.',
        type: 'fencing',
        email: 'info@escrimestrasbourg.fr',
        phone: '03 88 45 21 77',
        websiteUrl: 'https://escrimestrasbourg.fr',
        addressLine1: '10 Boulevard de Lyon',
        addressLine2: '',
        postalCode: '67000',
        city: 'Strasbourg',
        country: 'France',
        latitude: 48.5802,
        longitude: 7.748,
        isActive: true,
      },
      {
        name: 'Rennes Judo Club',
        description: 'Club de judo pour enfants, ados et adultes.',
        type: 'judo',
        email: 'contact@rennesjudo.fr',
        phone: '02 99 65 48 70',
        websiteUrl: 'https://rennesjudo.fr',
        addressLine1: '5 Rue de Brest',
        addressLine2: '',
        postalCode: '35000',
        city: 'Rennes',
        country: 'France',
        latitude: 48.1147,
        longitude: -1.6794,
        isActive: true,
      },
      {
        name: 'Montpellier Handball Formation',
        description: 'Formation handball pour jeunes talents.',
        type: 'handball',
        email: 'info@mhbformation.fr',
        phone: '04 67 72 33 11',
        websiteUrl: 'https://mhbformation.fr',
        addressLine1: '45 Rue de l’Université',
        addressLine2: '',
        postalCode: '34000',
        city: 'Montpellier',
        country: 'France',
        latitude: 43.6111,
        longitude: 3.8767,
        isActive: true,
      },
      {
        name: 'Nantes Badminton Club',
        description: 'Club de badminton avec plusieurs gymnases.',
        type: 'badminton',
        email: 'contact@nantesbadminton.fr',
        phone: '02 40 12 78 54',
        websiteUrl: 'https://nantesbadminton.fr',
        addressLine1: '3 Rue Léon Jost',
        addressLine2: '',
        postalCode: '44000',
        city: 'Nantes',
        country: 'France',
        latitude: 47.2184,
        longitude: -1.5536,
        isActive: true,
      },
      {
        name: 'Toulon Boxe Club',
        description: 'Club de boxe anglaise et française.',
        type: 'boxing',
        email: 'contact@toulonboxe.fr',
        phone: '04 94 01 22 40',
        websiteUrl: 'https://toulonboxe.fr',
        addressLine1: '18 Rue Jean Aicard',
        addressLine2: '',
        postalCode: '83000',
        city: 'Toulon',
        country: 'France',
        latitude: 43.1251,
        longitude: 5.9306,
        isActive: true,
      },
      {
        name: 'Angers Hockey Club',
        description: 'Club de hockey sur glace reconnu.',
        type: 'hockey',
        email: 'info@hockeyangers.fr',
        phone: '02 41 36 55 22',
        websiteUrl: 'https://hockeyangers.fr',
        addressLine1: '2 Boulevard du Roi René',
        addressLine2: '',
        postalCode: '49100',
        city: 'Angers',
        country: 'France',
        latitude: 47.4736,
        longitude: -0.5514,
        isActive: true,
      },
      {
        name: 'Dijon Cyclisme Club',
        description: 'Club de cyclisme pour amateurs et confirmés.',
        type: 'cycling',
        email: 'contact@dijoncyclisme.fr',
        phone: '03 80 45 78 65',
        websiteUrl: 'https://dijoncyclisme.fr',
        addressLine1: '22 Boulevard de Brosses',
        addressLine2: '',
        postalCode: '21000',
        city: 'Dijon',
        country: 'France',
        latitude: 47.3216,
        longitude: 5.0415,
        isActive: true,
      },
      {
        name: 'Tours Escalade Club',
        description: 'Club d’escalade avec murs intérieurs.',
        type: 'climbing',
        email: 'info@toursescalade.fr',
        phone: '02 47 45 88 90',
        websiteUrl: 'https://toursescalade.fr',
        addressLine1: '14 Rue Nationale',
        addressLine2: '',
        postalCode: '37000',
        city: 'Tours',
        country: 'France',
        latitude: 47.3941,
        longitude: 0.6896,
        isActive: true,
      },
      {
        name: 'Reims Athlétisme Club',
        description: 'Club d’athlétisme historique de Reims.',
        type: 'athletics',
        email: 'contact@reimsathle.fr',
        phone: '03 26 47 11 22',
        websiteUrl: 'https://reimsathle.fr',
        addressLine1: '30 Rue de Vesle',
        addressLine2: '',
        postalCode: '51100',
        city: 'Reims',
        country: 'France',
        latitude: 49.2583,
        longitude: 4.0317,
        isActive: true,
      },
      {
        name: 'Metz Danse Club',
        description: 'Club de danse moderne et classique.',
        type: 'dance',
        email: 'info@metzdanse.fr',
        phone: '03 87 12 11 44',
        websiteUrl: 'https://metzdanse.fr',
        addressLine1: '8 Rue du Grand Cerf',
        addressLine2: '',
        postalCode: '57000',
        city: 'Metz',
        country: 'France',
        latitude: 49.1203,
        longitude: 6.1778,
        isActive: true,
      },
      {
        name: 'Nancy Karting Club',
        description: 'Club de karting avec circuit homologué.',
        type: 'karting',
        email: 'contact@nancykarting.fr',
        phone: '03 83 41 87 22',
        websiteUrl: 'https://nancykarting.fr',
        addressLine1: '55 Rue Saint-Jean',
        addressLine2: '',
        postalCode: '54000',
        city: 'Nancy',
        country: 'France',
        latitude: 48.6921,
        longitude: 6.1844,
        isActive: true,
      },
      {
        name: 'Caen Gymnastique Club',
        description: 'Club de gymnastique féminine et masculine.',
        type: 'gymnastics',
        email: 'contact@caengym.fr',
        phone: '02 31 06 55 77',
        websiteUrl: 'https://caengym.fr',
        addressLine1: '6 Rue de l’Église',
        addressLine2: '',
        postalCode: '14000',
        city: 'Caen',
        country: 'France',
        latitude: 49.1829,
        longitude: -0.3712,
        isActive: true,
      },
    ]

    for (const club of clubs) {
      await Club.updateOrCreate({ name: club.name }, club)
    }
  }
}
