// layout.tsx
import type { Metadata } from 'next'
import { Figtree } from "next/font/google";
import { AuthProvider } from '@/contexts/AuthContext';
import ToasterProvider from '@/components/providers/ToasterProvider';

import './globals.css'

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree", // utile pour Tailwind
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <AuthProvider>
            {children}
            <ToasterProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
